name: Testes com Playwright

on:
  push:
    branches: [main] # Executa o workflow em cada push na branch 'main'
  pull_request:
    branches: [main] 

jobs:
  testes:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3 # Clona o repositório
      - uses: actions/setup-node@v3
        with:
          node-version: 16 
      - run: npm install 
      - run: npx playwright install 
      - run: npm run test 
      - run: npx allure generate ./allure-results --clean 
      - uses: actions/upload-artifact@v4 
        with:
          name: allure-report
          path: ./allure-results
      - name: Gera relatório Allure
        run: npx allure generate ./allure-results --clean

      - name: Publica relatório no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-results
